// List of moods with emojis and labels
final List<Map<String, String>> moods = [
//key: emoji, value '😘' key: label value: 'Happy'
  {'emoji': '😡', 'label': 'Angry'},
  {'emoji': '😖', 'label': 'Anxious'},
  {'emoji': '😬', 'label': 'Awkward'},
  {'emoji': '🙄', 'label': 'Bored'},
  {'emoji': '🙂', 'label': 'Calm'},
  {'emoji': '😶‍🌫️', 'label': 'Conflicted'},
  {'emoji': '😕', 'label': 'Confused'},
  {'emoji': '😌', 'label': 'Content'},
  {'emoji': '🤔', 'label': 'Curious'},
  {'emoji': '😶', 'label': 'Detached'},
  {'emoji': '😒', 'label': 'Disappointed'},
  {'emoji': '🤢', 'label': 'Disgusted'},
  {'emoji': '😳', 'label': 'Embarrassed'},
  {'emoji': '🤗', 'label': 'Excited'},
  {'emoji': '😩', 'label': 'Exhausted'},
  {'emoji': '😨', 'label': 'Fear'},
  {'emoji': '😤', 'label': 'Frustrated'},
  {'emoji': '😇', 'label': 'Grateful'},
  {'emoji': '😔', 'label': 'Guilty'},
  {'emoji': '😄', 'label': 'Happy'},
  {'emoji': '🫥', 'label': 'Indecisive'},
  {'emoji': '😢', 'label': 'Lonely'},
  {'emoji': '🫶', 'label': 'Loving'},
  {'emoji': '🫠', 'label': 'Melting'},
  {'emoji': '😐', 'label': 'Neutral'},
  {'emoji': '😵', 'label': 'Overwhelmed'},
  {'emoji': '😞', 'label': 'Regretful'},
  {'emoji': '😭', 'label': 'Sadness'},
  {'emoji': '🤯', 'label': 'Shocked'},
  {'emoji': '🤒', 'label': 'Sick'},
  {'emoji': '🥱', 'label': 'Sleepy'},
  {'emoji': '😣', 'label': 'Stressed'},
  {'emoji': '😴', 'label': 'Tired'},
  {'emoji': '🥹', 'label': 'Vulnerable'},
  {'emoji': '😟', 'label': 'Worried'},
];
